### ISSUE TITLE
Fix freeze of file: 1_test_postgres.R when run using Source

### ISSUE THREAD

**Issue by ianfrantz** [smithjd/sql-pet#12] opened 2018-08-26 18:27 UTC
**System command needs replaced with system2**
Line 46 will not successfully execute and will halt the script from proceeding.

`system("docker-compose up -d")`

**To Reproduce**
1. Run 1_test_postgres.R using Source (Ctrl+Shift+S)

**Expected behavior**
Running from Source should complete without any issues.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - V.1803
 - Version 1803

**Comment by ianfrantz** [comment] 2018-08-26 19:08
Looks like a path problem.

> Sys.which('whoami')
                             whoami 
"C:\\WINDOWS\\SYSTEM32\\whoami.exe" 
> Sys.which('docker')
docker 
    ""

**Comment by ianfrantz** [comment] 2018-08-26 23:15
system2 is not the answer to this problem.

**Comment by znmeb** [comment] 2018-08-26 23:30
I'll see if I can reproduce it - I didn't get that far yesterday but I can try it now.

**Comment by znmeb** [comment] 2018-08-26 23:38
OK - I can reproduce it. I also can get it from the command line, which gives me an actual error message:

```
$ docker-compose up -d
Starting sql-pet_dat_1 ... done
Starting sql-pet_postgres9_1 ... error

ERROR: for sql-pet_postgres9_1  Cannot start service postgres9: b'driver fa
iled programming external connectivity on endpoint sql-pet_postgres9_1 (364
4415932b4aa738b9e33126d198f13b28d0675181ae704eeee8e09f685cfc4): Error start
ing userland proxy: mkdir /port/tcp:0.0.0.0:5432:tcp:172.17.0.3:5432: input
/output error'

ERROR: for postgres9  Cannot start service postgres9: b'driver failed progr
amming external connectivity on endpoint sql-pet_postgres9_1 (3644415932b4a
a738b9e33126d198f13b28d0675181ae704eeee8e09f685cfc4): Error starting userla
nd proxy: mkdir /port/tcp:0.0.0.0:5432:tcp:172.17.0.3:5432: input/output er
ror'
ERROR: Encountered errors while bringing up the project.

znmeb@DreamGate  /d/znmeb/Projects/sql-pet (master)
```

I think I know what this is. Meanwhile, I think there's a way with both `system` and `system2` to capture the standard output and standard error from the command you ran - that's worth doing if we'll be issuing Docker commands from R.

**Comment by znmeb** [comment] 2018-08-26 23:48
Yep - this is most likely a bug in Docker Compose. If you search for the error `driver fa
iled programming external connectivity on endpoint` you will find many hits with both Mac and Windows hosts and with all sorts of services in containers. Here's one that's actually both recent and filed against Docker Compose: <https://github.com/docker/for-win/issues/2303>.

Go into the Docker Settings and restart Docker. It will probably work after Docker comes back up. That may be why we thought `system2` fixed it yesterday.

**Comment by smithjd** [comment] 2018-08-31 00:00
Running `1_test_postgres.R ` as source works correctly now.  The problem is with the YAML command in Windows.  Therefore this Issue is mis-named.  I think we should close it.

**Closed** 2018-09-01 21:26 UTC
